version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: tcp-chat-server

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: tcp-chat-client